# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Rohit Dureja
email: dureja@iastate.edu
description: Personal webpage of Rohit Dureja.
baseurl: ""
url: "http://www.rohitdureja.com"
twitter: rohitdureja
github:  rohitdureja
facebook: rohit.dureja

# permalink: "/notes/:year/:month/:day/:title"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
include: ['_pages']
plugins:
  - 'jekyll/scholar'
  - 'jekyll/feed'
  - 'jekyll-sitemap'

excerpt_separator: <!-- break -->

exclude:
  - docs/
  - notes/
  - Gemfile

# Scholar settings
scholar:
  style: _styles/association-for-computing-machinery.csl
  locale: en

  source: _bibliography
  bibliography: references
  bibliography_template: bib
  use_raw_bibtex_entry: true

  repository: assets/papers

  sort_by: year
  order: descending

  query: "@*"

